using System.Drawing;               // Font and Color: the palette work in ApplyTheme and the grey the button turns when it is disabled
using System.Windows.Forms;         // Form, Cursors and the control types this file touches
using PharmaLinkApp.Helpers;        // UiTheme (colours, ShowError/ClearError) and Validator (the field rules)
using PharmaLinkApp.Models;         // User, the object AuthService.Login hands back on success
using PharmaLinkApp.Services;       // AuthService, which owns the login query and the hash comparison

namespace PharmaLinkApp.Forms
{
    // -------------------------------------------------------------------------
    //  Layer: presentation.  Opened by Program.Main as the application's entry
    //  form. Uses AuthService (login), UserSession (identity), UiTheme (styling)
    //  and Validator (field rules).
    //
    //  Flow for a sign in:
    //      btnLogin_Click -> ValidateFields -> AuthService.Login
    //                     -> fill UserSession -> OpenDashboardFor(UserType)
    //
    //  There is no SQL in this file. The login query lives in AuthService.Login,
    //  which is the rule every form here follows: validate, call a service, bind
    //  the result.
    // -------------------------------------------------------------------------

    /// <summary>
    /// The single entry point of the application.
    ///
    /// There is no separate administrator login. All three roles type their
    /// email and password into this one form; the login query returns the
    /// UserType and that single value decides which of the three dashboards
    /// opens. No arrow in the navigation diagram ever crosses from one role
    /// branch into another.
    /// </summary>
    public partial class LoginForm : Form
    {
        // One service for the lifetime of the form. AuthService keeps no state and holds no
        // open connection - every call inside it opens a connection, runs and closes again -
        // so a single field is safe here and saves constructing one on every click.
        // readonly says the reference is assigned once: no later method can swap the service
        // out from under the click handler.
        private readonly AuthService _auth = new AuthService();

        public LoginForm()
        {
            // InitializeComponent is generated by the designer and creates every control on
            // the form. Nothing else belongs in the constructor: the window does not exist
            // yet at this point, so anything that can fail - and in particular anything that
            // touches the database - is done in LoginForm_Load instead, where a failure can
            // be shown in a label rather than crashing before a window has appeared.
            InitializeComponent();
        }

        private void LoginForm_Load(object sender, EventArgs e)
        {
            ApplyTheme();          // colours, fonts and the demo account list on the left panel
            UserSession.Clear();   // wipe any previous identity, so a stale PharmacyId cannot leak
                                   // into the next session if someone logs out and back in
            txtEmail.Focus();      // cursor starts in the first field
            ValidateFields();      // runs once on an empty form purely to DISABLE the button

            // Load, not the constructor, because these four lines all assume the controls are
            // created and the form is about to be shown. UserSession.Clear() in particular has
            // to run every time this form is displayed, which includes coming back from a
            // dashboard - see Dashboard_FormClosed, which clears it again for the same reason.
        }

        /// <summary>
        /// Applies the shared palette to this form and, at the end, makes the Login button
        /// the AcceptButton, which is what lets the Enter key submit the form. That single
        /// line is why btnLogin_Click re-runs the field rules instead of trusting that the
        /// button was enabled: Enter reaches the handler by a different route.
        /// </summary>
        private void ApplyTheme()
        {
            UiTheme.StyleForm(this, "Sign in");

            // ---- the branding panel on the left ----
            panelBrand.BackColor = UiTheme.Primary;

            lblBrandMark.Font = new Font("Segoe UI", 30F, FontStyle.Bold);
            lblBrandMark.ForeColor = Color.FromArgb(150, 220, 200);

            lblBrandName.Font = new Font("Segoe UI Semibold", 28F, FontStyle.Bold);
            lblBrandName.ForeColor = Color.White;

            lblTagline.Font = new Font("Segoe UI", 11F);
            lblTagline.ForeColor = Color.FromArgb(185, 225, 212);

            lblBrandBlurb.Font = UiTheme.FontBody;
            lblBrandBlurb.ForeColor = Color.FromArgb(210, 235, 226);

            lblDemoTitle.Font = new Font("Segoe UI Semibold", 8.5F, FontStyle.Bold);
            lblDemoTitle.ForeColor = Color.FromArgb(150, 220, 200);

            lblDemoAccounts.Font = UiTheme.FontMono;
            lblDemoAccounts.ForeColor = Color.FromArgb(220, 240, 234);
            lblDemoAccounts.Text =
                "Super Admin  admin@pharmalink.com.bd   Admin@123" + Environment.NewLine +
                "Pharmacy     kamrul@mitfordpharma.com  Pharma@123" + Environment.NewLine +
                "Pharmacy     shirin@dhanmondimedico.com" + Environment.NewLine +
                "                                       Pharma@123" + Environment.NewLine +
                "Pharmacy     tanvir@lazzcare.com       Pharma@123" + Environment.NewLine +
                "Customer     rahim@gmail.com           Cust@123" + Environment.NewLine +
                "Customer     nusrat@gmail.com          Cust@123" + Environment.NewLine +
                Environment.NewLine +
                "imran@newlifepharmacy.com is still Pending and" + Environment.NewLine +
                "is refused until the Super Admin approves it.";

            // ---- the login card on the right ----
            panelCard.BackColor = UiTheme.CardBack;
            panelCard.BorderStyle = BorderStyle.FixedSingle;

            lblTitle.Font = UiTheme.FontTitle;
            lblTitle.ForeColor = UiTheme.TextDark;
            lblSubtitle.Font = UiTheme.FontSmall;
            lblSubtitle.ForeColor = UiTheme.TextMuted;

            lblEmail.Font = UiTheme.FontBody;
            lblPassword.Font = UiTheme.FontBody;
            lblEmailError.Font = UiTheme.FontSmall;
            lblEmailError.ForeColor = UiTheme.Danger;
            lblPasswordError.Font = UiTheme.FontSmall;
            lblPasswordError.ForeColor = UiTheme.Danger;
            lblFormError.Font = UiTheme.FontSmall;
            lblFormError.ForeColor = UiTheme.Danger;

            lblNoAccount.Font = UiTheme.FontSmall;
            lblNoAccount.ForeColor = UiTheme.TextMuted;

            UiTheme.StylePrimary(btnLogin);
            btnLogin.Font = new Font("Segoe UI Semibold", 10.5F, FontStyle.Bold);
            UiTheme.StyleSecondary(btnGoSignUp);

            AcceptButton = btnLogin;
        }

        // ---------------------------------------------------------------------
        //  VALIDATION
        //  Both rules are checked as the user types. The Login button stays
        //  disabled until the email looks like an email and the password is at
        //  least six characters long, so an obviously wrong attempt never even
        //  reaches the database.
        // ---------------------------------------------------------------------

        private void Field_Changed(object sender, EventArgs e)
        {
            // One handler is wired to the TextChanged event of BOTH boxes in the designer,
            // which is why it uses neither sender nor e: whichever box changed, the whole
            // form is re-validated. Two near identical handlers would be two places for the
            // rules to drift apart.
            lblFormError.Visible = false;
            // The form level message says something like "That password is not correct", and
            // it belongs to the PREVIOUS attempt. The moment a character is typed that
            // sentence is stale, so it is hidden here rather than left on screen contradicting
            // what the user is now doing.
            ValidateFields();
        }

        private bool ValidateFields()
        {
            bool ok = true;      // stays true only if every rule below passes

            // The method both PAINTS the errors and RETURNS the verdict. That pairing is
            // deliberate: the click handler can call it again and get the same answer the
            // user is already looking at, with no second copy of the rules to keep in step.

            // -- email --------------------------------------------------------
            // Empty is not an error yet: the user has not finished typing, so clear
            // the message but still block the button. Showing red on an untouched
            // form would be shouting at someone who has done nothing wrong.
            if (Validator.IsBlank(txtEmail.Text))
            {
                UiTheme.ClearError(lblEmailError, txtEmail);
                ok = false;
            }
            // Something was typed but it is not an email shape. Validator.IsEmail
            // uses the same rule as CK_Users_Email on the Users table, so what the
            // form refuses is exactly what the database would refuse.
            else if (!Validator.IsEmail(txtEmail.Text))
            {
                // ShowError does three things at once: it writes the sentence into the small
                // red label under the box, makes that label visible, and tints the box itself
                // pink. Putting all three in one helper is what stops one screen from
                // reporting a problem in a way none of the others do.
                UiTheme.ShowError(lblEmailError, txtEmail, "That does not look like a valid email address.");
                ok = false;
            }
            else
            {
                UiTheme.ClearError(lblEmailError, txtEmail);   // valid, so remove any old message
            }

            // -- password -----------------------------------------------------
            if (Validator.IsBlank(txtPassword.Text))
            {
                UiTheme.ClearError(lblPasswordError, txtPassword);
                ok = false;
            }
            // Six is the minimum length the sign up form enforces, so anything
            // shorter cannot match a real account and is refused before it costs a
            // database round trip.
            else if (txtPassword.Text.Length < 6)
            {
                // Note this checks LENGTH only, not the "at least one digit" half of
                // Validator.IsStrongPassword. Sign up decides what a new password must look
                // like; login only has to reject what could not possibly be one. Applying the
                // full strength rule here would lock out any account created before the rule
                // existed, which is a login form refusing a password the database accepts.
                UiTheme.ShowError(lblPasswordError, txtPassword, "Password must be at least 6 characters.");
                ok = false;
            }
            else
            {
                UiTheme.ClearError(lblPasswordError, txtPassword);
            }

            // The button IS the validation result: disabled and grey until every rule
            // passes, so an obviously wrong attempt never reaches the database.
            btnLogin.Enabled = ok;
            // Enabled alone greys the TEXT but leaves the fill colour the theme gave it, so
            // the button would still look ready to press. Setting the BackColor as well makes
            // the disabled state visible from across the room rather than only on hover.
            btnLogin.BackColor = ok ? UiTheme.Primary : Color.FromArgb(170, 190, 184);
            return ok;
        }

        private void chkShowPassword_CheckedChanged(object sender, EventArgs e)
        {
            // PasswordChar is the character painted in place of each real one. '\0' is the
            // documented way to turn masking OFF - it means "no substitute character" - so
            // one assignment covers both directions and there is no second state to keep in
            // step with the tick box. The text itself is never altered, only how it is drawn,
            // so toggling the box cannot change what is eventually sent to AuthService.
            txtPassword.PasswordChar = chkShowPassword.Checked ? '\0' : '*';
        }

        // ---------------------------------------------------------------------
        //  LOGIN AND ROLE ROUTING
        // ---------------------------------------------------------------------

        private void btnLogin_Click(object sender, EventArgs e)
        {
            // Re-check the field rules even though the button is only enabled when
            // they pass: AcceptButton means Enter can also reach this handler.
            //
            // ApplyTheme sets AcceptButton = btnLogin, and Windows Forms raises that button's
            // Click event when Enter is pressed anywhere on the form. A disabled button is a
            // guard against the MOUSE, not against the keyboard, so without this line a user
            // who typed a two character password and hit Enter would go straight to the
            // database. Calling ValidateFields again costs nothing and closes that route.
            if (!ValidateFields()) return;

            Cursor = Cursors.WaitCursor;                 // this is a round trip to SQL Server
            try
            {
                string reason;                           // the service writes the refusal text here

                // One call does the whole sign in: read the Users row by email,
                // recompute the hash with that row's own salt, compare it in memory,
                // then check the account status and, for an owner, the shop status.
                // Trim the email because a trailing space would fail the = comparison.
                //
                // The password is deliberately NOT trimmed: a leading or trailing space is a
                // legitimate character in a password, and silently removing it here would make
                // an account created with one impossible to sign in to.
                User user = _auth.Login(txtEmail.Text.Trim(), txtPassword.Text, out reason);

                if (user == null)                        // null means refused; reason says why
                {
                    // One object, two outcomes: a User or null. The refusal TEXT travels in the
                    // out parameter rather than as a thrown exception, because "wrong password"
                    // is an ordinary outcome of a login, not a fault in the program.
                    UiTheme.ShowError(lblFormError, null, reason);
                    // null as the field argument means "no box to tint": the fault may be the
                    // email, the password, or the account's status, and guessing wrong would
                    // point the user at the wrong field.
                    txtPassword.SelectAll();             // select it so the next keystroke replaces it
                    txtPassword.Focus();
                    // Focus goes to the password, not the email, because a retyped password is
                    // the overwhelmingly likely fix. The email box keeps its text so a user who
                    // simply mistyped one character does not have to enter it all again.
                    return;                              // stay on this form, nothing was opened
                }

                // Copy the identity into the static session. THIS is the line that makes
                // data isolation work: every Admin query later reads PharmacyId from here,
                // never from a control, so there is nothing on screen a user could edit
                // to see another pharmacy's rows.
                //
                // Everything assigned below came out of the database row a moment ago. Because
                // this is the single place in the application where UserSession is filled, the
                // whole question "could a user widen their own scope?" reduces to reading these
                // six lines: no textbox, no grid cell and no command line argument is involved.
                UserSession.UserId = user.UserId;
                UserSession.FullName = user.FullName;
                UserSession.Email = user.Email;
                UserSession.UserType = user.UserType;    // decides which dashboard opens next
                UserSession.PharmacyId = user.PharmacyId;   // 0 for SuperAdmin and Customer
                // 0 rather than null: PharmacyId is an int, and AuthService's LEFT JOIN returns
                // NULL for anyone who owns no shop, which DbHelper.GetInt turns into 0. Any
                // query that carried 0 into a WHERE PharmacyId = @PharmacyId would match no
                // rows, so the failure mode of a mistake here is an empty grid, never another
                // shop's data.
                UserSession.PharmacyName = user.PharmacyName;

                OpenDashboardFor(user.UserType);         // the single role routing decision
            }
            catch (Exception ex)
            {
                // Reached when the database itself is unreachable. DbHelper has already
                // turned the SqlException into a readable sentence by this point.
                //
                // Catching Exception rather than SqlException is right HERE and nowhere else:
                // this is the outermost layer of a user action, and anything that escapes it
                // closes the application with a stack trace. The message names the setup script
                // because an unreachable database on a fresh machine is almost always a
                // database that has not been created yet.
                UiTheme.ShowError(lblFormError, null,
                    "Could not reach the database. Run PharmaLinkDB_Setup.sql first. (" + ex.Message + ")");
            }
            finally
            {
                Cursor = Cursors.Default;                // runs whether or not the login succeeded
                // finally, not a line at the end of try: an early return on a refused login and
                // a thrown exception both skip the end of the block, and either one would
                // otherwise leave the user staring at a spinning cursor on a form that is
                // waiting for them.
            }
        }

        /// <summary>
        /// The single decision node of the whole navigation diagram.
        /// One value, three destinations, and nothing else in the application
        /// ever has to ask again who the user is.
        /// </summary>
        private void OpenDashboardFor(string userType)
        {
            Form dashboard;      // declared first, assigned by exactly one branch below

            // Declared as the base type Form, so one variable can hold any of the three
            // dashboards and the Hide/subscribe/Show sequence below is written once instead of
            // three times. This is the practical payoff of inheritance in this project: the
            // three dashboards share no code, but they are all Forms, so they can be treated
            // identically the moment the choice has been made.

            // One string, three destinations. UserType comes from the Users table and
            // is constrained there by CK_Users_Type, so only these three values can
            // ever reach this switch.
            switch (userType)
            {
                case "SuperAdmin":
                    dashboard = new SuperAdminDashboard();   // platform operator
                    break;
                case "Admin":
                    dashboard = new AdminDashboard();        // pharmacy owner
                    break;
                case "Customer":
                    dashboard = new CustomerHomeForm();      // patient
                    break;
                default:
                    // Unreachable while the CHECK constraint holds, but a default that
                    // reports the problem beats one that silently opens nothing.
                    //
                    // It also keeps the compiler happy: without a branch that returns, the
                    // dashboard variable could be read before being assigned, and C# refuses
                    // to compile that. A default that returns is therefore both the safety net
                    // and the proof that every path through the switch assigns the variable.
                    UiTheme.ShowError(lblFormError, null, "This account has an unknown user type.");
                    return;
            }

            Hide();                                          // keep this form alive, just invisible
            // Hide, not Close. Program.Main started the message loop on THIS form, so closing
            // it would end the application the instant the dashboard opened. Hidden, it stays
            // alive as the thing the dashboard eventually returns to.
            // Subscribe BEFORE showing: when the dashboard closes, the handler brings
            // this form back and clears the session. That is how logging out returns
            // here without the application ever exiting.
            dashboard.FormClosed += Dashboard_FormClosed;
            dashboard.Show();                                // non modal, so this method returns
            // Show, not ShowDialog: a modal dashboard would block this method and freeze the
            // hidden login form behind it. Because Show returns immediately, the only thing
            // that brings this form back is the FormClosed event subscribed to on the line
            // above, which is why the order of these two lines matters.
        }

        /// <summary>Logging out closes the dashboard and brings this form back, cleared.</summary>
        private void Dashboard_FormClosed(object sender, FormClosedEventArgs e)
        {
            // Fires when ANY of the three dashboards closes, which is what "log out"
            // actually does. Clearing the session here rather than in each dashboard
            // means there is exactly one place that can forget to do it.
            //
            // It fires for every way a dashboard can close - the Log out button, the red X,
            // Alt+F4 - because FormClosed is raised by the form itself, not by any particular
            // button. A log out routine written in each dashboard would have to remember all
            // three routes, three times over.
            UserSession.Clear();
            txtPassword.Clear();               // never leave the last password in the box
            lblFormError.Visible = false;      // drop any refusal message from last time
            Show();                            // un hide the form that was hidden on sign in
            ValidateFields();                  // password is now empty, so disable the button again
            // Without this call the button would still be green and enabled from the previous
            // successful sign in, inviting a click on a form whose password box was just
            // emptied two lines ago.
            txtEmail.Focus();
        }

        private void btnGoSignUp_Click(object sender, EventArgs e)
        {
            // using() so the dialog is disposed even if it throws. SignUpForm is modal,
            // so execution stops on ShowDialog until the user finishes or cancels.
            //
            // A form shown with ShowDialog is NOT disposed when it closes, unlike one shown
            // with Show, so without using() every visit to the sign up screen would leak its
            // window handles and controls for as long as the application ran.
            using (SignUpForm signUp = new SignUpForm())
            {
                Hide();
                signUp.ShowDialog();           // blocks here
                Show();

                // RegisteredEmail is a property the dialog fills only for a CUSTOMER,
                // because a customer is created Active and can sign in immediately.
                // A pharmacy owner is created Pending and cannot, so the property stays
                // empty and nothing is pre-filled for them.
                //
                // Reading a property off the dialog AFTER it has closed is the standard way a
                // modal dialog reports a result. It works because the object still exists
                // until the closing brace of the using block, even though its window is gone.
                if (!string.IsNullOrEmpty(signUp.RegisteredEmail))
                {
                    txtEmail.Text = signUp.RegisteredEmail;
                    txtPassword.Clear();
                    // Cleared deliberately: the sign up form never hands the password back, and
                    // pre-filling a password box from anything would put a credential on screen.
                    txtPassword.Focus();       // straight to the only field still empty
                }
                ValidateFields();
                // Outside the if, so it runs on the cancel path too. Assigning txtEmail.Text
                // above raises TextChanged and would validate anyway; this call is what covers
                // the case where nothing was filled in and the button must go back to grey.
            }
        }
    }
}
